# Generated by Django 3.0.1 on 2019-12-28 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_post_likecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentonpost',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='likeoncomment',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='likeonpost',
            unique_together={('user', 'post')},
        ),
    ]
