# Generated by Django 3.0.1 on 2020-01-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20191228_2019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeonComment',
        ),
    ]
