# Generated by Django 3.0.1 on 2019-12-30 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20191228_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('follower_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_by_me', to=settings.AUTH_USER_MODEL)),
                ('following_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_for_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('follower_req', 'following_req')},
            },
        ),
    ]
